### ISSUE TITLE
ns build ios --release fails due to __esModule?

### ISSUE THREAD

**Issue by brandonros** [Notalib/nativescript-webview-ext#135]
```
$ ns deploy ios --release
Searching for devices...
Preparing project...
assets by status 1.25 MiB [cached] 4 assets
Entrypoint bundle = runtime.js vendor.js bundle.js
Entrypoint tns_modules/inspector_modules = runtime.js vendor.js tns_modules/inspector_modules.js
orphan modules 958 KiB [orphan] 99 modules
runtime modules 2.44 KiB 7 modules
modules by path ./node_modules/ 2.87 MiB
  javascript modules 2.61 MiB 244 modules
  json modules 273 KiB
    modules by path ./node_modules/mdn-data/css/*.json 242 KiB 3 modules
    modules by path ./node_modules/css-tree/ 30.7 KiB 2 modules
modules by path ./app/ 5.45 KiB
  modules by path ./app/*.ts 4.08 KiB 3 modules
  modules by path ./app/*.xml 925 bytes 2 modules
  ./app/__@nativescript_webpack_virtual_entry_typescript__ 238 bytes [built] [code generated]
  ./app/ sync \.(xml%7Cjs%7C(?<%21\.d\.)ts%7Cs?css)$ 244 bytes [built] [code generated]
external "~/package.json" 42 bytes [optional] [built] [code generated]

ERROR in ./node_modules/@nota/nativescript-webview-ext/webview-ext.ios.js + 2 modules
Cannot get final name for export '__esModule' of ./node_modules/@nota/nativescript-webview-ext/webview-ext.ios.js
while generating the root export '__esModule' (used name: '__esModule')
Error: Cannot get final name for export '__esModule' of ./node_modules/@nota/nativescript-webview-ext/webview-ext.ios.js
while generating the root export '__esModule' (used name: '__esModule')
    at getFinalBinding (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/optimize/ConcatenatedModule.js:469:10)
    at getFinalName (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/optimize/ConcatenatedModule.js:525:18)
    at /Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1416:24
    at ConcatenatedModule.codeGeneration (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/optimize/ConcatenatedModule.js:1464:7)
    at /Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/Compilation.js:3326:22
    at /Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Cache.get (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/CacheFacade.js:111:15)
    at Compilation._codeGenerationModule (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/Compilation.js:3319:9)
    at /Users/brandonros/Desktop/redacted/mobile-app/node_modules/webpack/lib/Compilation.js:3226:11
    at arrayIterator (/Users/brandonros/Desktop/redacted/mobile-app/node_modules/neo-async/async.js:3467:9)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

webpack 5.72.0 compiled with 1 error in 5700 ms
Executing webpack failed with exit code 1.

```

**Comment by brandonros** [comment]
probably https://github.com/triniwiz/nativescript-plugins/issues/88

**Comment by brandonros** [comment]
dupe of https://github.com/Notalib/nativescript-webview-ext/issues/128
